### ISSUE TITLE
Consider removal of try-catch library

### ISSUE THREAD

**Issue by Marak** [bigcompany/run-service#2]
`try-catch` uses domains. domains are and always have been terrible. we've lost stack traces are experiencing compatibly issues with `io.js`

the original use of `try-catch` for hook.io is no longer needed, as services are now run as child processes, uncaught errors can be thrown and picked up through stdout / stderr.

removing this type of error check from `run-service` will reduce the robustness of this individual library, but will not affect services being spawned as child processes. getting back stack traces and compatibly is important.

**Comment by joshgillies** [comment]
ref: https://github.com/CrabDude/trycatch/issues/41

**Comment by CrabDude** [comment]
Minor update at CrabDude/trycatch#41.

**Comment by Marak** [comment]
`trycatch` has been removed for some time.

We've been able to get enough isolation via `vm` module and child process spawn with https://github.com/stackvana/microcule. 

If an uncaught error bubbles up outside of the `vm` we should let the process crash.
